

development:
  adapter: mysql2
  encoding: utf8
  database: helix_dev1
  username: root
  password: password
  pool: 5

production:
  adapter: mysql2
  encoding: utf8
  database: helix_production
  username: helix
  password: 
  host: production.foo.com
  pool: 5
